{
  "formatVersion": "1.1",
  "component": {
    "group": "com.activeconnect.activeconnect",
    "module": "activeconnect",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "nmlglhz5t5e3zhmcld3leyugzu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "activeconnect-0.0.1.aar",
          "url": "activeconnect-0.0.1.aar",
          "size": 1054334,
          "sha512": "91a401a21df7aa88e7ab61d553bed238507c6e12618733a364fb4523ff45ff6eb81171680394ea308dd865c469e7e27dbe8246791901bb589f0de858c6116cda",
          "sha256": "a64c095a82b775461985194ca442f58f687924eb1b243feaee5b5dc9379902f2",
          "sha1": "170e5493eac1b8853b0c7e3ffda80a741680b8d6",
          "md5": "a0cfabec0415f75aa3426aca9c25dd02"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-barcode-model",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-image-label-model",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-face-model",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-model-interpreter",
          "version": {
            "requires": "22.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-object-detection-model",
          "version": {
            "requires": "19.0.3"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-automl",
          "version": {
            "requires": "18.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "activeconnect-0.0.1.aar",
          "url": "activeconnect-0.0.1.aar",
          "size": 1054334,
          "sha512": "91a401a21df7aa88e7ab61d553bed238507c6e12618733a364fb4523ff45ff6eb81171680394ea308dd865c469e7e27dbe8246791901bb589f0de858c6116cda",
          "sha256": "a64c095a82b775461985194ca442f58f687924eb1b243feaee5b5dc9379902f2",
          "sha1": "170e5493eac1b8853b0c7e3ffda80a741680b8d6",
          "md5": "a0cfabec0415f75aa3426aca9c25dd02"
        }
      ]
    }
  ]
}
