{
  "formatVersion": "1.1",
  "component": {
    "group": "com.activeconnect",
    "module": "activeconnect",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "plgpgrpshjby7f7a547kzsqquu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "activeconnect-0.0.1.aar",
          "url": "activeconnect-0.0.1.aar",
          "size": 1054337,
          "sha512": "4abe7748a7edecf5d6531e225627fef4b14d8cd4b5390a09a09cd0b11d3a8030dd291b5040385470abcdccb923dea8f9eb5de4a2c4d99b7728973d2a7c597092",
          "sha256": "152f8e57a6a60957f000aafbf86bf76bb6ede66e1d04b34367d059b3d98bd7c7",
          "sha1": "9638dfac5caed2d8b85dfb4ee39bb0e9bc3a0fc6",
          "md5": "a067e43e4d1d89517ff036100ad8fef6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-barcode-model",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-image-label-model",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-face-model",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-model-interpreter",
          "version": {
            "requires": "22.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-object-detection-model",
          "version": {
            "requires": "19.0.3"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision-automl",
          "version": {
            "requires": "18.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "activeconnect-0.0.1.aar",
          "url": "activeconnect-0.0.1.aar",
          "size": 1054337,
          "sha512": "4abe7748a7edecf5d6531e225627fef4b14d8cd4b5390a09a09cd0b11d3a8030dd291b5040385470abcdccb923dea8f9eb5de4a2c4d99b7728973d2a7c597092",
          "sha256": "152f8e57a6a60957f000aafbf86bf76bb6ede66e1d04b34367d059b3d98bd7c7",
          "sha1": "9638dfac5caed2d8b85dfb4ee39bb0e9bc3a0fc6",
          "md5": "a067e43e4d1d89517ff036100ad8fef6"
        }
      ]
    }
  ]
}
